// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignatureAPI.Persistence.Context;

#nullable disable

namespace SignatureAPI.Persistence.Migrations
{
    [DbContext(typeof(SignatureAPIDbContext))]
    [Migration("20260105102941_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SignatureAPI.Domain.Entities.Company.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("SignatureAPI.Domain.Entities.Signature.Signature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnvironmentText")
                        .HasColumnType("longtext");

                    b.Property<string>("Fax")
                        .HasColumnType("longtext");

                    b.Property<string>("InformationText")
                        .HasColumnType("longtext");

                    b.Property<string>("KdvText")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int>("SignatureType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("SignatureAPI.Domain.Entities.Signature.SignatureAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("SignatureId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SignatureType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SignatureId");

                    b.ToTable("SignatureAssets");
                });

            modelBuilder.Entity("SignatureAPI.Domain.Entities.Signature.SignatureLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LinkType")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("SignatureId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SignatureId");

                    b.ToTable("SignatureLinks");
                });

            modelBuilder.Entity("SignatureAPI.Domain.Entities.Signature.Signature", b =>
                {
                    b.HasOne("SignatureAPI.Domain.Entities.Company.Company", "Company")
                        .WithOne("Signature")
                        .HasForeignKey("SignatureAPI.Domain.Entities.Signature.Signature", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SignatureAPI.Domain.Entities.Signature.SignatureAsset", b =>
                {
                    b.HasOne("SignatureAPI.Domain.Entities.Signature.Signature", "Signature")
                        .WithMany("SignatureAssets")
                        .HasForeignKey("SignatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("SignatureAPI.Domain.Entities.Signature.SignatureLink", b =>
                {
                    b.HasOne("SignatureAPI.Domain.Entities.Signature.Signature", "Signature")
                        .WithMany("SignatureLinks")
                        .HasForeignKey("SignatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Signature");
                });

            modelBuilder.Entity("SignatureAPI.Domain.Entities.Company.Company", b =>
                {
                    b.Navigation("Signature")
                        .IsRequired();
                });

            modelBuilder.Entity("SignatureAPI.Domain.Entities.Signature.Signature", b =>
                {
                    b.Navigation("SignatureAssets");

                    b.Navigation("SignatureLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
